google_analytics: UA-160716658-1
plugins:
  - jekyll-redirect-from
kramdown:
  footnote_backlink: â†‘
sass:
  sass_dir: _sass
lang: ja
title: utelecon
repository: utelecon/utelecon.github.io
twitter:
  card: summary
defaults:
  -
    scope:
      path: ""
    values:
      lang: ja
      image: /assets/images/ogp.png
  -
    scope:
      path: en
    values:
      lang: en
      image: /assets/images/ogp.png
